Added a CLI and a debugger for the Scanner compatible with Linux and Windows.
RayverAimar/yarl pull request #6
Opened 2023-04-09 22:02 UTC by Alfred-CQ

1. CLI typer added
2. Arguments like path and --debug are necessary to open the program e.g. _python src/main.py --debug_ or _python src/main.py --debug file.txt_
3. The debugger was renewed
4. Output is compatible on Windows and Linux

2023-04-10 23:38 UTC, RayverAimar commented on include/yarl/scanner.py
It will be better not to overload the Scanner class with console outputs (if possible) as its objective is only scanning after all. Try to create a 'ConsoleHandler' class or sth similar which we can interact with, for parsing, scanning, and some other functions.

2023-04-10 23:39 UTC, RayverAimar commented on include/yarl/utils.py
Nice, that print_error function was not really helpful

2023-04-10 23:40 UTC, RayverAimar requested changes
Try to change (not to overload) the Scanner class as written in comments

2023-04-11 04:26 UTC, Alfred-CQ commented on include/yarl/utils.py
Yeah!

2023-04-11 04:34 UTC, Alfred-CQ commented on include/yarl/scanner.py
The scanner outputs have been separated so that they are handled by the ConsoleHandler class. An instance of the scanner has not been created within ConsoleHandler yet because as the parser is added, the class will be constructed

2023-04-12 14:50 UTC, RayverAimar approved these changes
Ok

2023-04-12 14:55 UTC, merged